// Mocks generated by Mockito 5.3.2 from annotations
// in home_challenge_kanban/test/features/export_kanban/data/export_data_services/mock/mock_export_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fast_immutable_collections/fast_immutable_collections.dart'
    as _i5;
import 'package:home_challenge_kanban/features/export_kanban/data/export_service/export_service.dart'
    as _i2;
import 'package:home_challenge_kanban/features/export_kanban/domain/entities/export_kanban.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportService extends _i1.Mock implements _i2.ExportService {
  @override
  _i3.Future<void> exportSingleKanban(_i4.ExportKanban? kanban) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportSingleKanban,
          [kanban],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> exportMultipleKanbans(
          _i5.IList<_i4.ExportKanban>? kanbans) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportMultipleKanbans,
          [kanbans],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
