// Mocks generated by Mockito 5.3.2 from annotations
// in home_challenge_kanban/test/features/kanban_history/data/datasource/mock/mock_kanban_history_local_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fast_immutable_collections/fast_immutable_collections.dart'
    as _i2;
import 'package:home_challenge_kanban/features/kanban_history/data/datasources/kanban_history_local_datasource.dart'
    as _i3;
import 'package:home_challenge_kanban/features/kanban_history/domain/usecases/read_time_range_finished.dart'
    as _i6;
import 'package:home_challenge_kanban/features/kanban_list/domain/entities/kanban.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIList_0<T> extends _i1.SmartFake implements _i2.IList<T> {
  _FakeIList_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString([bool? prettyPrint]) => super.toString();
}

/// A class which mocks [KanbanHistoryLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanbanHistoryLocalDatasource extends _i1.Mock
    implements _i3.KanbanHistoryLocalDatasource {
  @override
  _i4.Future<_i2.IList<_i5.Kanban>> readAllFinished() => (super.noSuchMethod(
        Invocation.method(
          #readAllFinished,
          [],
        ),
        returnValue:
            _i4.Future<_i2.IList<_i5.Kanban>>.value(_FakeIList_0<_i5.Kanban>(
          this,
          Invocation.method(
            #readAllFinished,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.IList<_i5.Kanban>>.value(_FakeIList_0<_i5.Kanban>(
          this,
          Invocation.method(
            #readAllFinished,
            [],
          ),
        )),
      ) as _i4.Future<_i2.IList<_i5.Kanban>>);
  @override
  _i4.Future<_i2.IList<_i5.Kanban>> readTimeRangeFinished(
          _i6.ReadTimeRangeFinishedParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #readTimeRangeFinished,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.IList<_i5.Kanban>>.value(_FakeIList_0<_i5.Kanban>(
          this,
          Invocation.method(
            #readTimeRangeFinished,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.IList<_i5.Kanban>>.value(_FakeIList_0<_i5.Kanban>(
          this,
          Invocation.method(
            #readTimeRangeFinished,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.IList<_i5.Kanban>>);
}
