// Mocks generated by Mockito 5.3.2 from annotations
// in home_challenge_kanban/test/features/export_kanban/data/datasources/mock/mock_export_kanban_local_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:home_challenge_kanban/features/export_kanban/data/datasources/export_kanban_local_datasource.dart'
    as _i2;
import 'package:home_challenge_kanban/features/export_kanban/domain/usecases/export_kanban_usecases.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ExportKanbanLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportKanbanLocalDatasource extends _i1.Mock
    implements _i2.ExportKanbanLocalDatasource {
  @override
  _i3.Future<void> exportSingleKabnan(_i4.ExportSingleKanbanParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportSingleKabnan,
          [params],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> exportMultipleKabnans(
          _i4.ExportMultipleKanbansParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportMultipleKabnans,
          [params],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
